Improved structure
HackYourFuture/browser-quiz-project-starter pull request #46
Opened 2022-01-30 15:47 UTC by tomasvanrijsse

Today in the presentations of the project I heard some students about the file structure of the project.
It took some of them one or even two days to get started because the new structure was daunting.

1. I've added a video to explain the structure
2. I've removed the router, the project is easier to understand without it

Since all projects look the same it became clear to me that students took the example really serious.
The list of tasks was taken as the actual requirements of the project.
And the project that was shown by Rob at the first Sunday was mimicked as good as the students could.
Therefore I changed the last part of the readme and added a few simple examples.

2022-02-06 12:16 UTC, robvk requested changes
The video is amazing!

I can understand wanting the teams to copy an end result. Usually I like giving them freedom so that they can go as far as they can, but giving them a goal will probably make it easier on them.

All great, only want to change the examples a little bit. Thoughts on the alternatives?

2022-02-06 12:16 UTC, robvk commented on README.md
> +- https://quiza.nl/raad-de-chips
This is a single page quiz so may get misinterpreted. Did a quick search, what do you think about:

- https://www.wizardingworld.com/quiz/the-first-year-hogwarts-houses-quiz
- https://openpsychometrics.org/tests/HEMCR/1.php
- https://www.lenstore.co.uk/vc/colour-is-in-the-eye-of-the-beholder/#/game
- https://heywise.com/quiz/lets-find-out-if-you-follow-gordon-ramsay/1/

2022-02-06 12:16 UTC, robvk commented on README.md
> +[![Project Structure YouTube Video](https://i.imgur.com/hDcLYFt.png)](https://youtu.be/bysBqtSKBpQ)
Really cool video, great idea starting with a single file and doing the splitting live! Thanks a lot for this

2022-02-06 19:22 UTC, tomasvanrijsse commented on README.md
> +- https://quiza.nl/raad-de-chips
I like your examples as well.
I'd only remove the psychological test, its UI isn't examplary and the theme a bit complicated.

2022-02-06 19:26 UTC, tomasvanrijsse commented
I think although we give them freedom, they seek for well defined requirements. Most teams therefore, stick to the format shown during the first meeting. Giving more examples should explain them that they actually have some freedom, i hope 🤷‍♂️

2022-02-07 11:38 UTC, robvk commented
Yeah, you may be right. Let's try it and see what happens! Will merge and then add the other examples :+1:

2022-02-07 11:38 UTC, merged